project:
  type: website

website:
  title: "My Data Project"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: "Home"
      - href: data.qmd
        text: "Data"
      - href: analysis.qmd
        text: "Analysis"
      - href: about.qmd
        text: "About"
    right:
      - icon: github
        href: https://github.com/zwcrowley/data_project

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 2
    toc-location: left

execute:
  freeze: auto

output-dir: _site



